M48
; DRILL file {KiCad 7.0.7+dfsg-1} date Thu 07 Sep 2023 11:36:28 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-07T23:36:28-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X1.2598Y-1.2106
X1.2598Y-4.8917
X4.9311Y-4.8819
X4.9409Y-1.2106
T0
M30
